### ISSUE TITLE
Period Metadata aquisition

### ISSUE THREAD

**Issue by max-vdL** [brembslab/DTSevaluations#1]
In readXMLdatafile.R: 
https://github.com/brembslab/DTSevaluations/blob/74fda16d323ab147f72564e11704fe089dd4e1fc/readXMLdatafile.R#L59

at the moment the list "metadata" expects as many entries as the first xml file suggested.
Problem: if the amount of Periods changes in one of the files, the expected entries won't be given.
-> make the length of "metadata[, l]" dependent on number of periods

**Comment by brembs** [comment]
Excellent point!
This is a general problem we need to discuss, not just for this function. In the main code, I check whether the experimental design is identical in all of the flies. We need to discuss what we do if it is not identical.
