### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AnEhw** [brembslab/DTSevaluations#116]
The new line for choosing the source file in the beginning is not working for me:
```
setwd(dirname(parent.frame(2)$ofile)) #set working directory to source file location (allows loading of function files)
Error in dirname(parent.frame(2)$ofile) : 
  a character vector argument expected
```

**Comment by AnEhw** [comment]
The dabest function is causing a probelm.

```
Error in dabest(PIstatPooled, group, PIs, idx = groupnames, paired = FALSE,  : 
  unused argument (func = mean)
```

If "func = mean is removed another error is occuring:

`
Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'print': 'language' object cannot be coerced to type 'double'`

**Comment by brembs** [comment]
One needs to look at all the variables to know what the problem is.
