### ISSUE TITLE
Fix idenitical OMParams graphs in project.Rmd

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#122]
All six OMParams (i.e., before and after) graphs are identical, but the tables are correct.

**Comment by AnEhw** [comment]
![Three group](https://user-images.githubusercontent.com/51921190/99528633-ddf00b80-299e-11eb-9dec-7acda56c2192.jpg)

**Comment by AnEhw** [comment]
![grafik](https://user-images.githubusercontent.com/51921190/99533529-56a69600-29a6-11eb-9d82-4250ea9b344f.png)
