### ISSUE TITLE
Make optomotor graphs prettier

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#13]
The graphs need to have a solid line at zero torque, the averaged curves should have shades and labels for left/right (CW(CCW) and so on. Some of the axes may also need some work.

**Comment by AnEhw** [comment]
![Opto](https://user-images.githubusercontent.com/51921190/60969481-e9014900-a31f-11e9-91a0-401da92301bf.PNG)

**Comment by AnEhw** [comment]
![Opto2](https://user-images.githubusercontent.com/51921190/60969557-1948e780-a320-11e9-9ce0-6e0b738cd6a9.PNG)

**Comment by AnEhw** [comment]
Here are the new graphs for the opto motor
![Opto1](https://user-images.githubusercontent.com/51921190/61201552-27fb1a00-a6e5-11e9-83f6-8dc11783e14e.jpg)
![Opto2](https://user-images.githubusercontent.com/51921190/61201556-2a5d7400-a6e5-11e9-8c34-5db2581cd865.jpg)
![Opto3](https://user-images.githubusercontent.com/51921190/61201559-2b8ea100-a6e5-11e9-8fc0-ce60e902ffd4.jpg)
![Opto4](https://user-images.githubusercontent.com/51921190/61201561-2d586480-a6e5-11e9-9146-bce10de67ae2.jpg)

**Comment by brembs** [comment]
Looks good! Now just make the line at zero torque stand out a bit more, so it's more visible than the other gridlines.
The X-axis [s] makes no sense if there aren't any seconds displayed :-)

**Comment by AnEhw** [comment]
I didn't notice that the function deletes the labels, so I'm using a different one now.
![Opto1](https://user-images.githubusercontent.com/51921190/61207253-eb371f00-a6f4-11e9-95eb-b8417e7935f1.jpg)
![Opto2](https://user-images.githubusercontent.com/51921190/61207254-ec684c00-a6f4-11e9-91df-03cfadc2608a.jpg)
![Opto3](https://user-images.githubusercontent.com/51921190/61207257-ed00e280-a6f4-11e9-8daa-2ef7aa262187.jpg)
![Opto4](https://user-images.githubusercontent.com/51921190/61207259-ee320f80-a6f4-11e9-8e45-62e9387c5311.jpg)

**Comment by brembs** [comment]
NIce!!

**Comment by brembs** [comment]
Found a small bug: left are counter-clockwise arena rotations...
