### ISSUE TITLE
Changing limit for plotting

### ISSUE THREAD

**Issue by AnEhw** [brembslab/DTSevaluations#136]
The range for the plotting of the trace in hardcoded at a range of -1800 to 1800 which cuts of the traces sometimes. 
In plotfunctions 29-42

```
dytraces <- function(rawdata)
{
  traces <- dygraph(rawdata, main = paste("Time Traces", flyname)) %>%
    dySeries("a_pos", label = "position", color = "darkred") %>%
    dySeries("fly", axis = 'y2', color = "blue") %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis("y", label = "Position [arb_units]", valueRange = c(-1800,1800)) %>%
    dyOptions(gridLineColor = "lightgrey") %>%
    dyAxis("y2", label = paste(FlyBehavior, "[arb units]"), independentTicks = TRUE, valueRange = maxfly, drawGrid = FALSE) %>%
    dyOptions(includeZero = TRUE) %>%
    dyRangeSelector()

  return(traces)
}
```
We should make it dynamic.

**Comment by brembs** [comment]
That is the limit for arena position (which must be 1800, because it can't be more than 180°). Torque s actually set my "maxfly" which is the range of the torque values...

**Comment by AnEhw** [comment]
Yes i also noticed that misstake. Then there is sometimes a problem with this calculation, because i still get plots like this:
![tracedrift](https://user-images.githubusercontent.com/51921190/119361117-99299200-bcab-11eb-9537-3d8c4510fca9.JPG)

Ofc in this case there was a clear drift, still there seems to be an issue.
