### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#18]
Us this thread to collect minor bugs. 

Here is the first one: The Y-axis in the halfmaximal OM rise time shows [rel. units] instead of [s].

**Comment by brembs** [comment]
Script does not heed statistics variable(s) in YAML file.

**Comment by Eanders1** [comment]
> Script does not heed statistics variable(s) in YAML file.

I believe this actually do work.

**Comment by brembs** [comment]
> Script does not heed statistics variable(s) in YAML file.

I found the bug: I also ask for two groups to exist. If there are two groups, the script will always do statistics. Let's discuss how to solve this, as the optomotor comparisons are not equally critical, but also depend on variable "two".

**Comment by brembs** [comment]
Fix Y-axis in rate constant of optomotor parameter estmation

**Comment by Eanders1** [comment]
The downsampling had a bug when  using Andi's data. His time is set in seconds and not milliseconds. The real_sample_rate was calculated to roughly 20 000. There is now an if clause that changes his time data to milliseconds.

**Comment by brembs** [comment]
Shiming torque meter data now also readable
