### ISSUE TITLE
Remove excess periods

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#47]
If there are more periods in the data than the meta-data specify, delete all the excess lines of data

**Comment by brembs** [comment]
Include scaling Andi's data to match the rest of the data.

**Comment by Eanders1** [comment]
In readXML file there is a line of code that has the comment "remove any extra periods numbers, if they exist"
The requested command is already existing in the code and no need to implement it again.

  ### check the dataframe for consistency
  if (length(table(rawdataDown$period)) > NofPeriods) {rawdataDown<-rawdataDown[!(rawdataDown$period==length(table(rawdataDown$period))),]} #remove any extra period numbers, if they exist

**Comment by brembs** [comment]
Excellent! I thought I had it somewhere... :-)

**Comment by Eanders1** [comment]
But I don't know why it didn't remove the periods from Andi's data?

**Comment by brembs** [comment]
This sequence is done only when the data get downsampled - is Andi's data getting downsampled?

**Comment by Eanders1** [comment]
Ah! That would explain it!

**Comment by brembs** [comment]
Let's copy the line in the downsample function to the main code in the readXML file.
