### ISSUE TITLE
If differences exist in metadata - find the differences and write them out

### ISSUE THREAD

**Issue by Eanders1** [brembslab/DTSevaluations#60]
The script does a good job finding if there are differences in the metafiles. It does not however tell you what the differences are. If you have 20-30 flies it is a tedious process to go through all of them to try to find the possibly one tiny difference that differs. 

It would be good if we could establish an error message that does not only tell you if there is a difference but also where and in which document it exists.

**Comment by brembs** [comment]
Yes, that would indeed be helpful!

**Comment by brembs** [comment]
Perhaps by collecting the meta-data and plot them in a table?

**Comment by brembs** [comment]
done
