### ISSUE TITLE
make conditional color graphs prettier

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#74]
After fixing the issues with conditional colors (see [clean up branch](https://github.com/brembslab/DTSevaluations/tree/clean-up)), we need to fix some issues with the graphs:
- the legend needs to be either smaller, or placed elsewhere
- we should experiment with transparency on the single fly dots
- aspect-ratio and size of the graphs need to be adjusted
- statistical and sample size annotations need to be adjusted.
- did I miss anything?

**Comment by brembs** [comment]
Oh, yes, let's think about a color scheme for the single fly dots!

**Comment by Eanders1** [comment]
[Test ggplotly_descr_anal.zip](https://github.com/brembslab/DTSevaluations/files/4586119/Test.ggplotly_descr_anal.zip)
