### ISSUE TITLE
compare multiplot and grid.arrange

### ISSUE THREAD

**Issue by brembs** [brembslab/DTSevaluations#92]
Let's see if one of the two is better (or a third one!) and if so make sure we ever only use the best one.

**Comment by AnEhw** [comment]
I tried ggarrange, grid.arrange and plot_grid. I was not able to see a differenc. But maybe there was some problem with my code.

**Comment by AnEhw** [comment]
![Plot Compair](https://user-images.githubusercontent.com/51921190/83615078-5fd1b100-a586-11ea-9d46-c86934714906.jpg)
